name: CI Workflow

on:
  pull_request:

jobs:
  ci-workflow:
    name: CI
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/complete-ci.yaml@main
    with:
      mauticVersion: 5
      skipCodeReview: true
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
